apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ip-claim-controller
  labels:
    app: ip-claim-controller
rules:
- apiGroups:
  - dcops.microscaler.io
  resources:
  - ippools
  - ipclaims
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - dcops.microscaler.io
  resources:
  - ippools/status
  - ipclaims/status
  verbs:
  - get
  - update
  - patch

