apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ip-claim-controller
  namespace: dcops-system
  labels:
    app: ip-claim-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ip-claim-controller
subjects:
- kind: ServiceAccount
  name: ip-claim-controller
  namespace: dcops-system

