apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ippools.dcops.microscaler.io
spec:
  group: dcops.microscaler.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - netboxPrefixRef
            properties:
              netboxPrefixRef:
                type: object
                required:
                - id
                properties:
                  id:
                    type: string
                  site:
                    type: string
              role:
                type: string
                default: ""
              allocationStrategy:
                type: string
                enum:
                - sequential
                - random
                default: sequential
          status:
            type: object
            properties:
              totalIps:
                type: integer
                format: int32
              allocatedIps:
                type: integer
                format: int32
              availableIps:
                type: integer
                format: int32
              lastReconciled:
                type: string
                format: date-time
  scope: Namespaced
  names:
    plural: ippools
    singular: ippool
    kind: IPPool
    shortNames:
    - ippool
    - ip

